spring:
  application:
    name: todo-app

  datasource:
    url: jdbc:postgresql:///${DATABASE_NAME}?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      sql:
        enabled: true
        databases-name: tododb
        instance-connection-name: ${CLOUD_SQL_CONNECTION_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: DEBUG
    com:
      main:
        todo: DEBUG